iso_name="Arch-Linux-ISO-PE"
iso_publisher=""
iso_application="Arch Linux Live/Installer"
iso_version="2024.01.01"
install_dir="arch"
buildmodes=('iso')
bootmodes=('bios.syslinux.mbr' 'bios.syslinux.eltorito' 'uefi-ia32.grub.esp' 'uefi-x64.grub.esp' 'uefi-ia32.grub.eltorito' 'uefi-x64.grub.eltorito')
arch="x86_64"
pacman_conf="pacman.conf" # Можно скопировать стандартный из /etc/pacman.conf
